# Generated by Django 5.2.6 on 2025-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=50, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность (дни)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.FloatField(verbose_name='Цена (USD)'),
        ),
    ]
